name: send email

on:
  push:
  schedule:
    - cron: '0 10 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'make script executable'
        run: bash ./execute.sh
      - name: 'SendGrid'
        uses: peter-evans/sendgrid-action@v1
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          #SCRIPT_FILEPATH: ./script/send-email.js
