name: send email

on:
  #push:
  schedule:
    - cron: '0 1 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weather.sh
      - name: 'Get Date'
        run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Xian' date '+%m-%d-%Y')"
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ${{env.REPORT_DATE}} Another day we are together.
          body: file://result.html
          to: wu_thor@foxmail.com
          from: GitHub Actions
          content_type: text/html
